# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "debian/jessie64"
  # config.vm.box_check_update = false
  # config.vm.network "private_network", ip: "192.168.37.10"
  # config.vm.synced_folder "./", "/home/vagrant/app"
  # config.vm.network "public_network"
end
